- src/components/RewardsPage/PoolDetail/index.tsx
> Go to correct contract link with round chain id

- src/containers/Footer/index.tsx
- src/containers/Footer/styles.ts
> feat: add audit reports link

- src/components/ClaimModal/index.tsx
- src/components/RewardsPage/PoolDetail/index.tsx
> feat: add pending status in farm claim modal

- src/constants/rewards/index.ts
> adjust: make farm pool archived

- src/constants/rewards/index.ts
> adjust: update archived pool

- src/containers/Footer/index.tsx
- src/containers/Footer/styles.ts
> feat: add Bug Bounty button in footer

- src/constants/index.ts
> feat: add new shakka addresses config

- src/components/StakingPage/StakePositionItem/index.tsx
- src/components/StakingPage/index.tsx
- src/constants/index.ts
- src/hooks/staking/useV1HakkaUnstake.tsx
- src/hooks/useContract.ts
useHakkaUnstake for new sHakka
useV1HakkaUnstake for v1 sHakka
> feat: useHakkaUnstake

- src/hooks/useStakedHakka.ts
> feat: useStakedHakka

- src/hooks/staking/useStakingRate.tsx
- src/hooks/staking/useStakingVault.tsx
- src/hooks/staking/useVaults.tsx
- src/utils/stakeReceivedAmount.ts
- src/utils/unstakeReceivedAmount.ts
> feat: formula for stake and unstake, and fetch data hook for calculation

- src/components/RedeemModal/styles.ts
- src/components/RestakeModal/index.tsx
- src/components/RestakeModal/styles.ts
- src/components/StakingPage/VotingPower/index.tsx
- src/components/StakingPage/VotingPower/style.ts
> Feature/modal UI rwd

- src/components/StakingPage/VotingPower/index.tsx
- src/components/StakingPage/index.tsx
- src/components/StakingPage/styles-v1.ts
- src/components/StakingPage/v1.tsx
- src/containers/VotingPowerContainer/index.tsx
> feat: v1 ui and rwd

- src/components/StakingPage/NavigateLink/styles.ts
- src/components/StakingPage/StakingPanel/styles.ts
- src/components/StakingPage/styles.ts
- src/components/StakingPage/v1.tsx
> adjust: ui layout and remove the banner in v1

- src/components/RewardsPage/index.tsx
> Avoid pool address is '' on farm pages

- src/components/Modal/styles.ts
- src/components/RedeemModal/styles.ts
- src/components/RestakeModal/styles.ts
- src/components/StakingPage/StakeInfo/index.tsx
- src/components/StakingPage/styles.ts
1. Complete the missing RWD part
2. Allow the user to scroll the modal
> adjust: modal RWD and staking info area RWD

- src/constants/tokenMetrics.ts
> adjust: fantom icon wrong bg color

- src/utils/rewardsApr.ts
- src/utils/stakeReceivedAmount.ts
> Add sHakkaV2Apr

- src/components/RewardsPage/RewardsPoolCard/index.tsx
- src/components/RewardsPage/index.tsx
> feat: farm pool card main button add hoc check chain

- package.json
- src/components/StakingPage/StakingPanel/index.tsx
> fix: input incorrect

- config/gatsby-node.ts
- src/constants/challenge.ts
- src/containers/SideBar/index.tsx
- src/pages/challenge.tsx
- src/templates/challengeDetail.tsx
> feat: add challenge and challengeDetail Route, add OAT_INFO

- src/components/ChallengePage/IntroPage/index.tsx
- src/components/ChallengePage/IntroPage/styles.ts
- src/components/ChallengePage/index.tsx
- src/components/ChallengePage/styles.ts
> feat: intro page

- package.json
- src/constants/challenge.ts
> adjust: add TM in upcoming mission item

- package.json
- src/components/ChallengePage/index.tsx
- src/templates/challengeDetail.tsx
> adjsut: add tutorial article link

- src/components/ChallengePage/CharacterStatus/index.tsx
- src/components/ChallengePage/CharacterStatus/styles.ts
- src/components/ChallengePage/MissionSection/index.tsx
- src/components/ChallengePage/index.tsx
- src/components/Common/Accordion/index.tsx
- src/constants/challenge.ts
clickup: CU-3qzhe4z, CU-3qzhe2z, CU-3qzjehu
> feat: update vl2 info, mission list display issue

- src/components/ChallengePage/MissionItem/index.tsx
- src/components/ChallengePage/MissionItem/styles.ts
- src/components/ChallengePage/MissionSection/index.tsx
- src/components/ChallengePage/index.tsx
- src/constants/challenge.ts
- src/hooks/useProjectGalaxyCampaignsInfo.ts
- src/images/index.tsx
> feat: update mission info, remove the test oat campaign

- package.json
- src/components/RewardsPage/PoolDetail/index.tsx
- src/constants/rewards/index.ts
clickup: CU-3xgxcnm, CU-3xgxdz8
> feat: archive farm term on fantom, fix withdraw error

- package.json
- src/components/NumericalInputField/index.tsx
> fix: staking max btn error when not connected

- package.json
- src/components/HomeScreen/component/TotalValueLock/index.tsx
> adjust: hide total value locked when api error

- src/components/ChallengeIntroPage/index.tsx
- src/components/RewardsPage/RewardsPoolCard/index.tsx
- src/components/StakingPage/StakingPanel/index.tsx
- src/components/VaultPage/index.tsx
- src/components/VestingPage/index.tsx
- src/components/WalletModal/index.tsx
- src/components/Web3Status/index.tsx
- src/hooks/useRequestNetworkConfig.ts
clickup: CU-86696f377
When the user is on an unsupported chain, it looks like this
with wrong network text
disable the connect btn
main btn guides the user to change networks
> feat: check unsupported chain in all dapp

- package.json
- src/components/RedeemModal/index.tsx
- src/components/RedeemModal/styles.ts
> feat: redeem modal position balance
